# Generated by Django 5.0.7 on 2024-08-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='UC', max_length=2, verbose_name='status'),
        ),
    ]
