# Generated by Django 5.0.7 on 2024-07-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/logos', verbose_name='photo'),
        ),
    ]
